# Generated by Django 3.2.15 on 2022-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Url'),
        ),
    ]
