# Generated by Django 3.2.15 on 2022-08-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Url'),
        ),
    ]
